### PR TITLE
Add a build support for mac/aarch64

### PR DESCRIPTION
**Pull request by stevebriskin**
Tested on my M1 macbook, where "Tested" means it built and tests passed. I don't have access to a windows or x64 macos environment.

CMAKE_SYSTEM_PROCESSOR on macos will be the same as `uname -m` which is `arm64` or or `x86_64`.

mac/aarch64 [build output](https://gist.github.com/stevebriskin/1a93d832f30d739e0450e6e50a275a89).

Note:
I wasn't sure which way to proceed to set the TARGET_CPU in the cmake build files (I don't know cmake). I chose to do it in the cmake file rather than passing `-Aarm64' from maven. Primary reason being, "cmake -A<arch>" isn't supported in unix environments with the default "Unix Makefiles" generator. Here is the alternative where this logic is in maven. [See diff.](https://github.com/devopvoid/webrtc-java/compare/master...stevebriskin:webrtc-java:macarm64?expand=1)

Additionally, I'm not sure if the current Windows profile in webrtc-jni's pom.xml works, as the [quotes around  {cmake.options}](https://github.com/devopvoid/webrtc-java/blob/master/webrtc-jni/pom.xml#L94) are passed to cmake command (e.g. `....cmake "-Ax64" ....` instead of `...cmake -Ax64 ...`)  and on my mac the -A option with quotes is ignored. Removing quotes (and pre-defining cmake.options) fixes this on my mac. Worth doublechecking intended behavior on Windows.

### CODE REVIEW

**Comment by devopvoid** [comment]
Great and thank you!

The current Windows profile in webrtc-jni's pom.xml works.

**Comment by devopvoid** [comment]
Now we need macarm64 CI cross-compilation. I'll add one next weeks.

**Comment by stevebriskin** [comment]
I'm puzzled as to why mac x86 builds are failing. i'll debug. you may have to approve more workflow runs.

**Comment by devopvoid** [comment]
Does my commit work on your M1 machine?

**Comment by stevebriskin** [comment]
> Does my commit work on your M1 machine?
It does

**Pull request merged**
